spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_studio_test
    username: postgres
    password: xx123456XX
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.mydotey.ai.studio.handler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

file:
  storage:
    local:
      upload-dir: ${java.io.tmpdir}/ai-studio-test-uploads
